#!/bin/bash

if [ -z "$BFG_SHELL_HOME" ]; then
    export BFG_SHELL_HOME="$HOME/.bfg_shell"
fi

SHOULD_CLONE=0
if [ -z "$BFG_SHELL_NO_CLONE" ]; then
    if [ -f "$BFG_SHELL_HOME" ] || [ -d "$BFG_SHELL_HOME" ]; then
        echo
        echo "ERROR!"
        echo
        echo "A directory or file already exists at $BFG_SHELL_HOME."
        echo
        echo "If you want to udpate an existing installation of BFG Shell, "
        echo "simply run bfg_update. If you have already cloned the repo and"
        echo "set \$BFG_SHELL_HOME and just need setup, re-run this script"
        echo "with BFG_SHELL_NO_CLONE=1 set in the environment."
        echo
        exit 1
    fi

    SHOULD_CLONE=1
fi

ZSHRC_FILE="$HOME/.zshrc"
NEEDS_CLEANUP=0
if grep -q "## BEGIN:BFG_SHELL ##" "$ZSHRC_FILE" && \
        grep -q "## END:BFG_SHELL ##" "$ZSHRC_FILE"; then
    NEEDS_CLEANUP=1
fi

echo
echo "Welcome to the BFG Shell installer."
echo
echo "This script is provided to you under the terms of the license agreement"
echo "that should have been distributed with this program. See LICENSE."
echo
echo "The installer will perform the following actions:"
echo
if [ "$SHOULD_CLONE" -eq 1 ]; then
    echo " - The BFG Shell repository will be cloned to $BFG_SHELL_HOME"
else
    echo " - Per your instructions, your existing BFG Shell install located"
    echo "   at $BFG_SHELL_HOME will be used and clone will not occur."
fi
if [ "$NEEDS_CLEANUP" -eq 1 ]; then
    echo " - Anything between \"## BEGIN:BFG_SHELL ##\" and "
    echo "   \"## END:BFG_SHELL ##\" will be deleted from $ZSHRC_FILE"
fi
echo " - The BFG Shell initializer will be added to your $ZSHRC_FILE"
echo " - BFG Shell scripts will be sourced into this shell session."
echo

while true; do
    printf "Would you like to proceed? [y/n]: "
    read -r REPLY
    case $REPLY in
        [yY]) echo ; break ;;
        [nN]) echo ; echo "Abort!"; echo; exit 1 ;;
        *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac
done

if [ "$SHOULD_CLONE" -eq 1 ]; then
    git clone git@github.com:BenJetson/bfg_shell.git "$BFG_SHELL_HOME"
fi

if [ "$NEEDS_CLEANUP" -eq 1 ]; then
    sed "/## BEGIN:BFG_SHELL ##/,/## END:BFG_SHELL ##/d" "$HOME/.zshrc" \
        | tee "$HOME/.zshrc"
fi

cat << EOF >> "$ZSHRC_FILE"
## BEGIN:BFG_SHELL ##

# It is strongly recommended that you do not edit this section.
# This section is automatically generated by the BFG Shell installation program
# and future versions may overwrite this segment of your .zshrc.

export BFG_SHELL_HOME="$BFG_SHELL_HOME"
source "\$BFG_SHELL_HOME/init.sh"
bfg_init

## END:BFG_SHELL ##
EOF

source "$BFG_SHELL_HOME/init.sh"
bfg_init

(
    source "$BFG_SHELL_HOME/splash.sh"
    bfg_splash
)

echo
echo "Installation complete. BFG Shell has been initialized here."
echo "Restarting your shell is recommended."
echo
